FROM python:3.11.6-bookworm

WORKDIR /home

RUN git clone https://github.com/lapps-xdd/xdd-docstructure code/xdd-doctructure \
	&& git clone https://github.com/lapps-xdd/xdd-processing code/xdd-processing \
	&& git clone https://github.com/lapps-xdd/xdd-terms  code/xdd-terms

